language: csharp

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libunwind8 gettext libssl-dev libcurl3-dev zlib1g libicu-dev
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
  - dnvm upgrade -r coreclr

script:
  - echo "script"