language: csharp
mono:
 - beta

install:
	curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
	apt-get install libunwind8 gettext libssl-dev libcurl3-dev zlib1g libicu-dev
	dnvm upgrade -r coreclr

script:
  cd projects/ZenSendTest && dnu restore && dnx . test