language: bash
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - libunwind8
      - gettext
      - libssl-dev
      - zlib1g
      - libicu-dev

install:
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
  - dnvm install `grep -oP '(?<=")1.0.0[0-9a-zA-Z\.\-]*(?=")' global.json` -r coreclr -alias default
  - dnvm list

script:
  - dnvm use default
  - dnu --version